services:
  - type: web
    name: codearena-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health