services:
  - type: web
    name: codearena-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 8000
    healthCheckPath: /health